[en]
  title = "My English Site"
  languageName = "English"
  contentDir = "content/en/"
  menuFile = "en.toml"
  weight = 1
  rss = true
[fr]
  title = "My English Site"
  languageName = "French"
  contentDir = "content/fr/"
  menuFile = "fr.toml"
  weight = 2
  rss = true
[ru]
  title = "My English Site"
  languageName = "Russian"
  contentDir = "content/ru/"
  menuFile = "ru.toml"
  weight = 3
  rss = true

