[[menu.main]]
      weight = 1
      identifier = "posts"
      name = "Posts"
      url = "/posts/"
[[menu.main]]
      weight = 2
      identifier = "about"
      name = "About"
      url = "/about/"
[[menu.main]]
      weight = 3
      identifier = "tags"
      name = "Tags"
      url = "/tags/"
[[menu.main]]
      weight = 4
      identifier = "categories"
      name = "Categories"
      url = "/categories/"