[[menu.main]]
      weight = 1
      identifier = "posts"
      name = "Postes"
      url = "/fr/posts/"
 [[menu.main]]
      weight = 2
      identifier = "about"
      name = "À propos"
      url = "/fr/about/"
 [[menu.main]]
      weight = 3
      identifier = "tags"
      name = "Balises"
      url = "/fr/tags/"
 [[menu.main]]
      weight = 4
      identifier = "categories"
      name = "Catégories"
      url = "/fr/categories/"