[[menu.main]]
      weight = 1
      identifier = "posts"
      name = "Статьи"
      url = "/ru/posts/"
    [[menu.main]]
      weight = 2
      identifier = "about"
      name = "Про блог"
      url = "/ru/about/"
    [[menu.main]]
      weight = 3
      identifier = "tags"
      name = "Тэги"
      url = "/ru/tags/"
    [[menu.main]]
      weight = 4
      identifier = "categories"
      name = "Категории"
      url = "/ru/categories/"
